/* QHR-35 */
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Zod schemas — single source of truth for shape + runtime validation
// ---------------------------------------------------------------------------

/**
 * Schema for creating a new employee.
 * `id` is intentionally omitted — it must be generated by the database.
 * `salary` is stored as an integer (cents) to avoid floating-point precision
 * issues in payroll calculations (SUGGESTION fix).
 */
export const CreateEmployeeSchema = z.object({
  name: z.string().min(1, 'name is required').max(200),
  email: z.string().email('email must be a valid email address'),
  position: z.string().min(1, 'position is required').max(200),
  /** Salary stored in cents (integer) to avoid floating-point precision errors. */
  salary: z.number().int('salary must be an integer (cents)').nonnegative(),
});

/**
 * Schema for updating an existing employee.
 * All fields are optional; `id` is never accepted from the caller.
 */
export const UpdateEmployeeSchema = CreateEmployeeSchema.partial();

// ---------------------------------------------------------------------------
// TypeScript types derived from the schemas
// ---------------------------------------------------------------------------

/** Full employee record as stored / returned from the database. */
export interface IEmployee {
  id: string;
  name: string;
  email: string;
  position: string;
  /** Salary in cents (integer) to avoid floating-point precision errors. */
  salary: number;
}

/** DTO for creating an employee — `id` excluded so the DB generates it. */
export type CreateEmployeeDto = z.infer<typeof CreateEmployeeSchema>;

/** DTO for updating an employee — all fields optional, no `id`. */
export type UpdateEmployeeDto = z.infer<typeof UpdateEmployeeSchema>;

/**
 * Public-facing employee response that omits sensitive fields (e.g. salary)
 * for callers that do not hold an elevated role.
 * Authorised roles (HR Admin, Finance) receive the full IEmployee object.
 */
export type PublicEmployeeDto = Omit<IEmployee, 'salary'>;

// ---------------------------------------------------------------------------
// Typed error hierarchy used across service / controller layers
// ---------------------------------------------------------------------------

export class NotFoundError extends Error {
  public readonly statusCode = 404;
  constructor(message = 'Resource not found') {
    super(message);
    this.name = 'NotFoundError';
  }
}

export class ValidationError extends Error {
  public readonly statusCode = 400;
  constructor(message: string) {
    super(message);
    this.name = 'ValidationError';
  }
}
